# Generated by Django 5.0 on 2024-02-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_people', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=100)),
                ('seat_capacity', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('places_to_visit', models.TextField()),
            ],
        ),
    ]
