# Generated by Django 5.0 on 2024-02-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tror', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='phone_number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
