# Generated by Django 5.0 on 2024-02-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tror', '0002_travelbooking_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
